# Generated by Django 3.1.7 on 2021-03-19 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginprojectapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='profile_pc',
            new_name='profile_pic',
        ),
    ]
